FROM python:3.9-slim

WORKDIR /app

RUN apk add --no-cache gcc musl-dev libffi-dev

RUN pip install --upgrade pip

COPY packages.txt ./

RUN pip install --no-cache-dir -r packages.txt

COPY . .

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "wsgi:app"]
